global:
  scrape_interval:     15s
  evaluation_interval: 15s
  external_labels:
      monitor: 'm3db-compose'
remote_write:
  - url: http://coordinator:7201/api/v1/prom/remote/write
scrape_configs:
  - job_name: 'prometheus'
    scrape_interval: 10s
    static_configs:
      - targets: ['prometheus:9090']
  - job_name: 'm3db'
    scrape_interval: 10s
    static_configs:
      - targets:
        - 'node01:9004'
        - 'node02:9004'
        - 'node03:9004'
  - job_name: 'm3coordinator'
    scrape_interval: 10s
    static_configs:
      - targets: ['coordinator:7203']
